### ISSUE TITLE
Transform JSON from analytics-reporter into geojson

### ISSUE THREAD

**Issue by laurenancona** [laurenancona/parkadelphia#9]
Currently, custom events such as `Show Info`, `User located` and `Address Search` are being logged with coordinates by an instance of [analytics-reporter](https://github.com/18F/analytics-reporter) (currently deployed to Heroku free tier, refreshed hourly) in an [s3 bucket](https://s3.amazonaws.com/lauren-analytics-reporter/data/user-searches.json) on AWS.

Need to write a little script to read json in the above format to a layer we can load as geojson via mapbox-gl-js, and display as an overlay on the map, style TBD. The idea is to give a rough approximation of the locations where users are seeking regulation information.

**Comment by laurenancona** [comment]
Luckily, someone just up the street wrote a little library just for this sort of thing: https://github.com/caseypt/GeoJSON.js

**Comment by chriswhong** [comment]
This functionality is added in [this PR](https://github.com/laurenancona/parkadelphia/pull/10)

Still needs a legend.

**Comment by laurenancona** [comment]
Oh grrrr, @chriswhong; strict mode doesn't like this nested [function](https://github.com/laurenancona/parkadelphia/pull/10/commits/958296ab900699a01fff71e84b71a782f814e7b1#diff-aaaa4e286fd3d7e125192fa362aeaf36R320) when testing in Safari/Firefox.

Throwing `SyntaxError: Strict mode does not allow function declarations in a lexically nested statement.`

**Comment by themightychris** [comment]
if you remove the name after the `function` keyword and instead just assign an anonymous function to `requent.onload` it will be a function expression instead of a function declaration and pass

**Comment by laurenancona** [comment]
Thanks, @themightychris! Will do for now. 
Out of curiosity, I'm juuuust starting to learn to write unit tests per @mjumbewu.  It seems as if making that an anon function might make it more difficult to test?

**Comment by themightychris** [comment]
Not really, the function is equally untestable either way

**Comment by themightychris** [comment]
The downside of anonymous functions is that in stack traces you won't see a useful name. The problems with testing it having nothing to do with whether it's named or anonymous

**Comment by laurenancona** [comment]
Bweh, Safari still doesn't like the nested function.
